In [21]:
import numpy as np
import random
from sklearn.model_selection import train_test_split

from IPython.display import Audio, display
def allDone():
    urL = 'http://www.wavsource.com/snds_2020-03-30_7102365145747638/animals/cat_meow2.wav'
    display(Audio(url=urL, autoplay=True))
# allDone()

random.seed(666)

motifs = np.genfromtxt('data__for_nerds/motifs.csv',dtype='U')
motifxFamMatrix = np.genfromtxt('data__for_nerds/motifxFamMatrix.csv',delimiter=',',dtype=int)
fams = np.genfromtxt('data__for_nerds/fams.csv',dtype='U')

print(len(motifs))

7866


In [29]:
X_train, X_test = train_test_split(range(len(motifs)), test_size=0.15, random_state=666)

train_motifs = motifs[X_train]
test_motifs = motifs[X_test]

In [19]:
from Bio import SeqIO

results = '1588970924.result/1588970924.fas.db2novel.clstr.sorted'

fasta_sequences = SeqIO.parse(open(results),'fasta')
for i,fasta in enumerate(fasta_sequences):
    name, sequence = fasta.id, str(fasta.seq)
    print(i,sequence.split())
    if i==1000:
        break

0 ['0', '15aa,>1818...*1', '15aa,>595...at80.00%2', '15aa,>711...at60.00%3', '15aa,>776...at60.00%4', '15aa,>1137...at60.00%']
1 ['0', '15aa,>4134...*1', '15aa,>107...at60.00%2', '15aa,>255...at86.67%3', '15aa,>496...at80.00%4', '15aa,>665...at60.00%']
2 ['0', '15aa,>848...*1', '15aa,>429...at53.33%2', '15aa,>612...at46.67%3', '15aa,>657...at80.00%']
3 ['0', '15aa,>2156...*1', '15aa,>114...at53.33%2', '15aa,>528...at66.67%3', '15aa,>1168...at80.00%']
4 ['0', '15aa,>2268...*1', '15aa,>128...at93.33%2', '15aa,>585...at60.00%3', '15aa,>854...at53.33%']
5 ['0', '15aa,>2763...*1', '15aa,>113...at53.33%2', '15aa,>385...at53.33%3', '15aa,>1123...at46.67%']
6 ['0', '15aa,>3911...*1', '15aa,>201...at60.00%2', '15aa,>329...at53.33%3', '15aa,>755...at60.00%']
7 ['0', '15aa,>4101...*1', '15aa,>82...at80.00%2', '15aa,>866...at93.33%3', '15aa,>1024...at46.67%']
8 ['0', '15aa,>4237...*1', '15aa,>310...at60.00%2', '15aa,>418...at80.00%3', '15aa,>611...at46.67%']
9 ['0', '15aa,>6486...*1', '15aa,>186..

960 ['0', '15aa,>6338...*1', '15aa,>289...at73.33%']
961 ['0', '15aa,>6365...*1', '15aa,>804...at86.67%']
962 ['0', '15aa,>6368...*1', '15aa,>260...at46.67%']
963 ['0', '15aa,>6374...*1', '15aa,>844...at73.33%']
964 ['0', '15aa,>6375...*1', '15aa,>767...at53.33%']
965 ['0', '15aa,>6376...*1', '15aa,>963...at46.67%']
966 ['0', '15aa,>6377...*1', '15aa,>111...at46.67%']
967 ['0', '15aa,>6401...*1', '15aa,>98...at60.00%']
968 ['0', '15aa,>6418...*1', '15aa,>818...at60.00%']
969 ['0', '15aa,>6420...*1', '15aa,>935...at86.67%']
970 ['0', '15aa,>6443...*1', '15aa,>1160...at46.67%']
971 ['0', '15aa,>6446...*1', '15aa,>590...at86.67%']
972 ['0', '15aa,>6447...*1', '15aa,>433...at60.00%']
973 ['0', '15aa,>6450...*1', '15aa,>64...at53.33%']
974 ['0', '15aa,>6456...*1', '15aa,>492...at93.33%']
975 ['0', '15aa,>6460...*1', '15aa,>1144...at60.00%']
976 ['0', '15aa,>6461...*1', '15aa,>266...at53.33%']
977 ['0', '15aa,>6464...*1', '15aa,>919...at73.33%']
978 ['0', '15aa,>6472...*1', '15aa,>45...at46.

In [117]:
m1 = train_motifs[2268]
m2 = test_motifs[128]

print(m1, m2, m1[7], m2[7])

i1 = np.where(motifs==m1)[0][0]
i2 = np.where(motifs==m2)[0][0]

print(i1,i2)

fi1 = np.where(motifxFamMatrix[i1]==1)[0]
fi2 = np.where(motifxFamMatrix[i2]==1)[0]
print(fi1)
print(fi2)

print(motifxFamMatrix[i1])
print(motifxFamMatrix[i2])

print(fams[fi1])
print(fams[fi2])

SYAGGRGSYGDLGGP YAGGRGSYGDLGGPI S Y
1089 5235
[0 6]
[4]
[1 0 0 0 0 0 1 0]
[0 0 0 0 1 0 0 0]
['PKA' 'PKC']
['SRC']


## Find Hamming-near motifs between test and train sets.

In [190]:
### https://biology.stackexchange.com/questions/23523/hamming-distance-between-two-dna-strings
def inv_hamming_distance_COPYPASTA(s1, s2):
    #Return the Hamming distance between equal-length sequences
    if len(s1) != len(s2):
        raise ValueError("Undefined for sequences of unequal length")
    return sum(ch1 == ch2 for ch1, ch2 in zip(s1, s2)) / len(s1)

In [191]:
def inv_hamming_distance(s1, s2):
    #Return the Hamming distance between equal-length sequences
    if len(s1) != len(s2):
        raise ValueError("Undefined for sequences of unequal length")
    zipped = zip(s1,s2)
    ### don't want to count "empty" characters ...
    max_buff_length = max( sum([1 for c in s1 if c=='_']), sum([1 for c in s2 if c=='_'])  )
    return (sum((ch1 == ch2 and ch1 != '_' and ch2 != '_') for ch1, ch2 in zip(s1, s2)) / 
            (len(s2)-max_buff_length) )

In [192]:
t1 = 'GEDEESESD______'
t2 = 'AEEKEAKSD______'

print(inv_hamming_distance(t1,t2))
print(inv_hamming_distance_COPYPASTA(t1,t2))

print(inv_hamming_distance_COPYPASTA('GEDEESESD','AEEKEAKSD'))
print(inv_hamming_distance('GEDEESESD','AEEKEAKSD'))

0.4444444444444444
0.6666666666666666
0.4444444444444444
0.4444444444444444


In [166]:
import time
import itertools

start = time.time()
similar_motifs = []
for i,combo in enumerate(itertools.product(train_motifs, test_motifs)):
    score = inv_hamming_distance(combo[0],combo[1])
    if score >= 0.6:
        print(score, combo)
        similar_motifs.append( [combo[0], combo[1], score] )
    if i%100000==0:
        print(i,combo)
print("%5.3f mins" % ((time.time()-start)/60))
allDone()


0 ('DKVEIYKSFRPGDIV', 'NIHIKDASQTTLLDL')
0.6 ('SPGAPGGSGSQPNQK', 'VPEAPGGSAV_____')
0.6 ('KEVEDKESEGEEEDE', 'KAARVLGSEGEEEDE')
0.6 ('PSWLRRASAPLPGLS', 'ASPARRASAILPGVL')
0.8 ('SAAAAIVSPEEELDG', 'PAADAIMSPEEELDG')
0.8666666666666667 ('GETLPDSTPLGFYLR', 'GETLPDSTPLGLYLK')
100000 ('RFRFNSESESGSEAS', 'SLLKKSSSFRTPRDS')
0.6666666666666666 ('______MSSKKAKTK', 'MIFDPTMSKKKKKKK')
0.6666666666666666 ('______MSSKKAKTK', '___MSSESSKKRKPK')
0.6666666666666666 ('GIPIRVYTHEVVTLW', 'GSPNRAYTHQVVTRW')
0.6 ('_____MSSPPPARSG', 'PSEPMMSTPPPASEL')
0.6666666666666666 ('SRRSRSRSRSRSPGR', 'SPRRRRRSRSRSRSR')
0.6 ('AVEEDAESEDEEEED', 'DQPEDAGSEDELEEG')
0.9333333333333333 ('ESSPLPTSPKFLRPN', 'ESSPLPTSPKFLRQN')
200000 ('QGSQGWDSQSDTVLL', 'KKGKRPPTPCSDPER')
0.8666666666666667 ('LKKSLRQSFRRMRRS', 'LKKSLRQSFRRIRKS')
0.8 ('DTRQIQPSPPWSYDQ', 'DPRQAQSSPPWSYDQ')
300000 ('KTHSVPATPTSTPVP', 'HQLFRGFSFVATGLM')
0.6 ('HTPKTADSQETKESQ', 'HTPKTDDSQEKTDDS')
0.8666666666666667 ('ERVSRKMSIQEYELI', 'ERFSRKMSVQEYELI')
0.8 ('RNSPVTK

0.9333333333333333 ('ILDNNGTYGKIWEGS', 'IPDNNGTYGKIWEGS')
0.9333333333333333 ('WAKGRHETYLCYVVK', 'WAKGRRETYLCYVVK')
0.6666666666666666 ('GYRDSGYYWEVPPSE', 'GQRDSSYYWEIEASE')
0.9333333333333333 ('NAALRRESQGSLNSS', 'NSALRRESQGSLNSS')
3600000 ('LIPVETLTPEIALYW', 'VAGQIRATQQQHDFT')
0.7333333333333333 ('GILARRPSYRKILKD', 'EILSRRPSYRKILNE')
0.8 ('PRHSIYSSDEDDEDF', 'PRHSIYSSDDDEEDV')
0.6 ('ELVSSSSSGSDSDSE', 'EHDSDESSDDDSDSE')
0.9333333333333333 ('SGMKRSRSGEGEVSG', 'SGVKRSRSGEGEVSG')
0.8 ('PTETAESSQAEEEKD', 'PTETAESSQAEEKIE')
0.9333333333333333 ('QSVYIPMSPGPHHFD', 'QSVYIPMSPGAHHFD')
0.9333333333333333 ('PPVRRRSSANYRAYA', 'APVRRRSSANYRAYA')
3700000 ('NILPDQTSQDLKSKE', 'KTHEILGSLEDRNGE')
0.6 ('EEPLEDESEIEEFYN', 'PRPLRRESEI_____')
3800000 ('_PKRKVSSAEGAAKE', '___MKALSPVRGCYE')
0.6666666666666666 ('YKPPPQKSLKELQEM', 'YKPPAQKSIQEIQEL')
0.8 ('QMDRVDQSAVGFEYQ', 'QADRVDKSAVGFDYQ')
0.6 ('CKGFFRRTIRLKLAY', 'CKGFFRRSVRKNHMY')
0.6666666666666666 ('LSRERGESPTAPPPA', 'PGRERGESPTTPPTP')
0.6 ('KEGDVDVSDSDDEDD

0.6 ('GRYKSTTSVSEEDVS', 'GRYKSTISAPEEEIL')
0.8 ('TPVVSVATPTLPGQG', 'TPVVSVTTPSLPPQG')
7200000 ('FDGIWKASFTTFTVT', 'GSVQNPVYHNQPLNP')
0.8 ('DDIDLFGSDEEEDKE', 'DDIDLFGSDDEEESE')
0.6 ('RLIVDDEYNPQQGTK', 'RLIEDNEYTARQGAK')
0.6666666666666666 ('RHRHRSRSSSRSRSR', 'SPRRRRRSRSRSRSR')
0.6 ('RHRHRSRSSSRSRSR', 'RKKHRSRSRSRERRS')
0.9333333333333333 ('RKGQRDLYSGLNQRA', 'RKGQRDLYSGLNQRR')
7300000 ('RKGQRDLYSGLNQRA', 'RQKGKRSSSDYAQRE')
0.6666666666666666 ('VPLLREASARDRQSA', 'VPLLRDASTRDRHAT')
0.6428571428571429 ('ARRPDPDSDEDEDYE', 'NRRKVMDSDEDDDY_')
0.7333333333333333 ('AAVDSDMYDLPKKED', 'TRGDADMYDLPKKED')
0.9333333333333333 ('KELQRQASPSIVIAL', 'KELQRQASPNIVIAL')
7400000 ('SSTGSPTSPLNAEKL', 'VDEGQLASEEEEAEH')
0.9333333333333333 ('TDPEALHYDYIDVEM', 'TDPGALHYDYIDVEM')
0.6 ('LFKSATTTVMNPKFA', 'IYKSAVTTVVNPKYE')
0.6 ('TPKYSPTSPTYSPTS', 'SPRYTPQSPTYTPSS')
0.8 ('TPKYSPTSPTYSPTS', 'SPTYSPTSPKYSPTS')
0.7333333333333333 ('TPKYSPTSPTYSPTS', 'SPSYSPTSPKYTPTS')
0.6 ('AGESLDQSMEEEEEE', 'EGEEEDVSGEEEEDE')
7500000 

In [187]:
sim_train = [x[0] for x in similar_motifs]
sim_test = [x[1] for x in similar_motifs]

print(len(set(sim_train)))
print(len(set(sim_test)))

271
218


In [185]:
MY_IDX = 16

t1 = similar_motifs[MY_IDX][0]
t2 = similar_motifs[MY_IDX][1]

i1 = np.where(motifs==t1)[0][0]
i2 = np.where(motifs==t2)[0][0]

print(i1,i2)

fi1 = np.where(motifxFamMatrix[i1]==1)[0]
fi2 = np.where(motifxFamMatrix[i2]==1)[0]
print(fi1)
print(fi2)

print(motifxFamMatrix[i1])
print(motifxFamMatrix[i2])

print(fams[fi1])

print(fams[fi2])

5256 6192
[2 3 7]
[7]
[0 0 1 1 0 0 0 1]
[0 0 0 0 0 0 0 1]
['CDK' 'MAPK' 'PIKK']
['PIKK']
